### ISSUE TITLE
You don't need to abuse regex

### ISSUE THREAD

**Issue by gosoccerboy5** [LankyBox01/ImpactJSON#8]
this is pretty cool. but in the code I see that you use a lot of regexps to replace a lot of text. You know you can use `<string>.replaceAll(text1, text2)` instead of `<string>.replace(/text1/g, text2)`
it makes things more readable in my opinion, especially when you don't have to escape everything.

**Comment by LankyBox01** [comment]
.replaceAll doesn't work in nodejs, so i had to use regex with the /text/gi so it replaces all.

**Comment by CST1229** [comment]
> 
> 
> .replaceAll doesn't work in nodejs, so i had to use regex with the /text/gi so it replaces all.

Can't you use `string.replace("text", "text2")`?

**Comment by gosoccerboy5** [comment]
> > .replaceAll doesn't work in nodejs, so i had to use regex with the /text/gi so it replaces all.
> 
> Can't you use `string.replace("text", "text2")`?

sadly that only replaces the first instance of a string

**Comment by gosoccerboy5** [comment]
I threw together a quick replacement for String.replaceAll
```node
Object.defineProperty(String.prototype, "replaceAll", {
    enumerable: false,
    value(str, replace) {
        if (str instanceof RegExp) throw new Error("this polyfill doesnt support using regexes in string.replaceAll");
        return this.replace(RegExp(
            str.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&') // https://github.com/no-context/moo/blob/a8dd4/moo.js#L22
        , "g"), replace);
    }
});

console.log("hello world".replaceAll("l", "w"));
```
if you like, you can add an implementation that allows regex using RegExp.prototype.source, RegExp.prototype.flags, and RegExp.prototype.global.

**Comment by gosoccerboy5** [comment]
I made an implementation that allows both regex and strings for `replaceAll`
```node
Object.defineProperty(String.prototype, "replaceAll", {
    enumerable: false,
    value(str, replace) {
        if (str instanceof RegExp){
            if (str.global) {
                return this.replace(RegExp(str.source, str.flags), replace);
            }
            return this.replace(RegExp(str.source, str.flags + "g"), replace);
        }
        return this.replace(RegExp(
            str.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&') // https://github.com/no-context/moo/blob/a8dd4/moo.js#L22
        , "g"), replace);
    }
});

console.log("hello world".replaceAll("l", "w"));  // hewwo worwd
console.log("hello world".replaceAll(/l/, "w"));  // hewwo worwd
console.log("hello world".replaceAll(/l/g, "w")); // hewwo worwd
```

**Comment by gosoccerboy5** [comment]
Helo? @LankyBox01

**Comment by LankyBox01** [comment]
> Helo? @LankyBox01

I'm not gonna add more dependecies unless it's **absolutely required**

**Comment by LankyBox01** [comment]
if you don't have any other reasonble suggestions then I'll close this

**Comment by gosoccerboy5** [comment]
> > Helo? @LankyBox01
> 
> I'm not gonna add more dependecies unless it's **absolutely required**

> if you don't have any other reasonble suggestions then I'll close this


Alright, chill. I guess 10 lines of code to add a .replaceAll polyfill is too extreme
