### ISSUE TITLE
why is index.js obfuscated in some parts

### ISSUE THREAD

**Issue by gosoccerboy5** [LankyBox01/ImpactJSON#9]
that scares away potential contributors like me.
while I [could use a prettifier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEcAmBLGAKTWgDE8AbOTAXkwCc4BHAVz0YAoAdEXAgWgBWJKPwBmlODwCUAbi5QAbgEN62AB4AHRmjS0GzNpwDkcLTrTHpClWuWbN+s9ri6O1qAoD0XzABFoYywAWwh8MQBPTGUoKM1VLAgxTBgACzw9CSoAQm9fABUITDAWDAhgvAAvagiIFjUAdzgAIzQCOAAaTABzIpg+1Oom1vaAOmFoTCzqJA8FKixpp3wiEXIqDgADABJgAH09-HooZWC4AF8vYbb4cZFNuXm4LBYoLPhGHAP9adHu5-c8igCymlA+uG+dEIAGUAPIAOVGGHoeCg3TwkQ4r3ecE+B2ko0YmgoyjAcA4XgAPF50V0eAAyCgweQgAlEklkikAPhpeDpIHp3WZMkJcGJpPJXgA2tsALpcLgcDhS5qMZQAa2ksoA1NYuNJefzKaquSL2RKKVLjNtjPLFcrmhAKDgtbqFQbaZgeMbTazReLOV4FUqrV5bSqnS6dXqPXyvSBqc1fWyxRzJVabXaQwRlBQ8GBXTHDfHKXhk-60xTg8rjGHZVKc3mC9H3cXvV4y2bUxbpdbbdWpa8cLi81A4IXW57vSxy+bAwPa+GhyPUeOW-q2wmvDOuwH032s8rR5r17GjcpMKlGGIaMZd5Wg-bQ+HjxON1OQMYuQAZVHq6nKLO3aBhm-ZPngwTKP8b5niWEHdJgaD0GAt73j2C51g2kHQaem7GJgXhAXuloHla9C2puREPqB9bGBQFEfpSMiyARvh4JeyjwAY-zqJgXJINwwLPAwygNJCmAwgiozxPQaDkjieJ7I8nhvK8YAwHgkz-DAACCMAwCizTuMAjAwPUUDRPphl7Ko9DKBEUoAAzqI5srnLItiWQZeDNDZ9B2VEdBWmAUAQBpZK2ixnkHJAmgRCi3SpPAJzNFQOD6HZYl7FK2l6d5Rlapg2R0FALAUBQmD0vSIlZTlzx5YZ7iyrQdAGSwcAsT4mAAMKDGA6pTBAdiIXAYCmV5hksFxYC5ml8YhWF+ZSCACh5Jg+SDNgsDsNQJyKHg3ScZpFnNKomCotEl4sP8mCjtQSTFGE1AUJBEBPFgBx7d1sLfhlokHKM8LKPth0adAozQs8GlomggPAwdR3QHsABCqh7N1TpDbIIJ7QjYNQLIuOg8d+g8DwHlnUlwQVUFmyUnmXKUheV5wDePCbF0mw8FyHOYHTXiAdSDObLKshiGp+OYHtBzaQAEvkACy34cJoEBoNIJnPOZl4wNTUqq2govuWIQ2YBwnnqnAUQXZlBxWkDIOI1AtoaxiHCW4FdA8JD+mot0aAyI922lR1nkqBQ7V-VlcOO-jUoe6LRNO-oSeS9qUvAzLzzy0rHCOdImDp5JiLIn7GIRObubtQSaBNuSACMHT8PXBfp9Lexy4ryst4XElwiX3louX7tWzXdccI3zetxnihZzAOfKwATHI7mpyTJXw8Tkzp3TeaITAERUDQPBiBQECcUgCVJSy504MfIBoKkEANJAw4HNzTOXte99eK-y1ctCJ+DQepPQAozLwwsgRrT8KzVcmBBDA2UGgMaeBNBYGqjNZByh8Bon3ofagj84DPFhgoSAUAMCYAVjQWWYsJYk0UMZMhFDkY0CtPXAAzPXeu0IFaohIMYDoxgAAsAB2AAnOwgArJIxeFAFY4HhGIHAAjjCLxETIgAHJIkR8IqgAGkADqigVEKhcsoSkGB8Gmi4GYx0OAIimMXo5YApjHLKEcY5Dxp1+rdHoHUKAOAkAePoN0Iyi8hGN3CZEiJjwbFuI8V40k6pfH+MCR4-goRKj8DuqofgvjsF4AQDACeGjHLDm6B0YJoTlAcCiR0OpdSW4eMcgAUkqTYpxITTq1OkfU3pi9elNI6Y5eujlWmxLMQk4Z3jkl+KHEE4Z-BhjqgEDk+geS7L4CKSUspcAKlVO6Q0iJ9TjlDPUE41p7TzmOS6TUgZki+kPPuR0M5TjRnjPkHE9xwzEk+LmQEhZ1y1kbIKds+upTylXM6dU2pxyjmN1eWMtpBy7n9LRQ8xF7yWkTPiT84ZClAVOO0BAdEgS-AAA0ACS2E4D5DsuQk29BgijF4WNNWSQYB-E2YU2AHAMAJAxmfWSBlj4dMXgAYjEPXKVUrHGLw6AgHAgqhrIlFeciVYhNVarlR0AA4tyop+QIiaDgDQFunzJl4uuSbWA4hTiUAiISxygwKCKGePmZQFrcXXI8ZBEJqInWOU0OoL13yfXDMGAdJKTqsWhqmdcmZKShz8CJHAC+HjQoprFGm4UXz41OMTf8nA-BOIwFJKkM4sAnUSHULgUN5xXFhrcdJKCUhhkuLzVapxfr0RQCdUSkNjaG2drMWGpxHbLXhuuZAIVTrfFW3rY2xtzQpr9E8O2pdXbHKOnoMOdZ3LShOskcGxdI63FlQ8RO71TiPF5gwPwSxVB+AHxNU60KY441bp7QG5pn6p1EuwTg7oga-03uGRAN19BT7PydekHAw4Cabv-dupJSaAn8BnUNJ1KjF64bEYvVIel-YAFUVEADZpESLGQAJV1QARWCMEVIKjT2TrcXmS9SGwPWrPum4ZVAxC5rMcOtjuY8AeLHc4rjnjhn4DQOKR1Xiz79VAzJ6dmN6BOoaOkeAqmPHwHUDAEteZuh9o8WSWAuI9PDPiPBv2MahHBo8fXMjJ7pP6bMEZ4ckA7L4zfdADqQ6kPsfE8M5QSAn6Qc4yO7jBbUNFowxpp14rtHKEkZq1j3rm0mzCriaLk7YuOQM0ZsTpmnUWY+NZhN8XUmJdnbeqNMB50RCq04zDmmPHiuld1sQrWg1qwIMdJ1yhWhOimoFmLamC1hX6MEED7nhlXxgPNybt7WbLd-Qt65tmgNOqEUGwdXyRNuOpI+uA1izE4ccgALQAKLfigNdsQJivkWJQWgi7bimFOjgKMM+3RuBioVtgtt1yGgEFSB46l8R1LF1GHKnFpJ0A-b+ySwH6qkowE0GgJAPh0RpBYM0UYkBgheG-DEdUERkYQBcvXLw0PSREH7o+dViPTvvZgJ95QKjJG3YAAp6NSMR-IKj64iMchAPnstRqkcEewsRbqDGkG-MYwRGiyP4bI45FXqQjHO0Eeo9hjkhGL3UPkZoTBrsAE1IqKBoOLKA6ljrGVMtrZGsh3Ku+OJgBhK8mFYHhNQ2Q-vMDkqDxwB3TvoAcEqB0CgGsQ9oCDyHylyf0BYG6Gn8hWBmhZ4oTeGhIfbt56wMRkv51y9QHLzAcv1Hy+whoJUQE2nJAcGyNkKUsoNYGQiMAEPOkaAyTkpS3laA87qA19IA0zl64ACoOD8CH3AEfxSx-OQo1Prwzll7akX6oYfvKAfr7I5v5y7D5979ksv3lRl18umn+oIR0htRL5XxwSl4+yNP4f5I+fr+b+f4aKn4T7P6X4H7FIf7r4iLAEiK77-7FJiCf7KDAEaIv777X7FK3af7NDAFiJ-7oFv7FLOTi7AHIFoFX5v5YHr7jgP7NCyBuwD40A0Dx7ACqhprqge5wAUByTACwhWiaClDMaygcB8HGCPwYgwC2juArznAzQwBgCpAcAGIayiECGPxSGiHiGCZSFT4e7nDnDmwdDOQaLNAiLy66GR6Syywx5x4J7p6YAN6+6yCyz250LR46QdDKHAAD46T8Dr5CLYzCRJ58E6Sixe4WRoAe6yDhGYDWGx7x4e4ghnYHA0AKyf4FjaifTAzfTfjahpHr5iByAgiogEApHwjj4iLmqrRQBuy2x7Axx4zHQQxQx+ywy3YpRUB7AOyNFIyoz0AayeR7T6B0xlQ8y9xrzbx8zUijGbCcHcFwDACDHAykwrQgAe7VFuwxQQBxRLYIAjZpQDFnQLThTUB0B0z4CKDFAki6D3w5YfDcybC9x1FwxnC9yPEACVICOxjWfM4xcAwCfgnE5IBI2kpAZUFAVuaa9A7gbxowmAOk5UDAjWegOguIbqOAow1IFxPMcxPBnkxxS0Kx5M5wrE8J8Gj03xiUiwEAuW9AXQGII0Y0wkpak0XEGQ0Q8GuA1RXUlKpmQ01AaQGQ9JkhegMQHJFQFk8QY4FUjKiE5Qzw6QaI8OQkWAqIggo0WAZxb2KIH2Ie341CHQuessHQVuBpeAQelhJM+QjC9hVeUoPA2klK8AwQPAHQnEEARkPAVuBi1GZaBi6W5KjkDQ6g8I3QMglS4Aao8At2VAlaMArpPAFxCZ4A1xaAQMZwyZ2CEpUpXByZZ2yZhaqSyq9AyZkqi8Yg5Zi8yZBsg20AmZo2Ec8AyZAm8ZIAEZ-QmgBZM25QyZ4OOAaQyZ9cTmbZPA7WpZ2ikicA6i1ZgGfsg5B2mA9cx6vEjkmAA6yZqIY49AC8yZFiUpmA0AYATY6ot42xexOA2ZMQXBgIgpsMjAoQbq7g+EZ2t4JQskWGqsqIHwX44C8mMQvoEZvCugfsmAJqTKGQbQ6AuQI5IA2kMZcAcZaAyMEQ3UqZ6Zy0EZYuy5u5qQi8XIOkF5F0OZFA1IuFjMK6+kkwh5x5t44OASz8qOchTRjAvGOAT5XI1GXB58OAiYq60AjMV4AlQiXIG07J1w7QpFwlxofFFk1F+YJ5xguYuIxSrw+xRC-kwQaA3Q0gX40IpQJqASvFlFUAXImA-AmA0lxlB5juNFilVA9AKlHR6lTKWlOlXIt2KwRla65F9APl5FMl1lR58lt4SlDlWITluILl2lulZaDllCygX5exjucAXl-FlIgl6VwlCJFUNwrgkl-lVlcl-UIV9ljlalkVml0VACsVWAwOiVJwyVqVJlXZ9imZDgiqG55CylBFCCFWO5MFzQrM-J7ROAu5Z2XIdive36ogLZSAQiy55wp2B8VAjM41FFa6mArBQ0e6SAmAjksgO6e6KaBSh6i5B2B1NWya7Wu14qQiOAYiIiGWO29mZ1J611mALeumb5JAmmoFEAiV9AHuS1ViPAYRWsxwHA+Qrhju+MLu4NFkUA5w0g7gsh9h0IBpYexpd8xpEABp3UBpdGBpfgBpKExpuqBpqQBpDexpA+xpdexpSexpVexpBeHQfOBpBiBplQBppqxpLCxpJ5xpduxpgeNClpkw1hUAHQMAdh2e2ANA1pcg4RHALh4tUAHAUtMtmsZk3ucAUoogNArkSNGt0t0gqNct6gBppAQebspU5UxUymuY0I-Qdk-wUoys+cwh3cU+GsOMNAOAEAJQcZUoVutSWoHAys7CuhUAKoHAT+soNA0IHAki0gHQMdysJ+9YRk0BCdeAHAQBad7tHAmdUofgHAYiWoNA5KE8+chd1dJdZdXCldPAnibZMdEAxdWopdE8y8CdLdrpMdRkJdodHCzdIArdhdedJdih9c8dNARkS5qdMddGnd9YedLmldBiE80Bhdihw9JSld1d9cFdhdK9TildY+i85qnkqlqUzllVNA5RuGcgatB5BlWZqIxFNpctzN0tPNBpuNNCAdQdRS+ttSUdwhxSKd0gTk9Y6tJdxSs9ldHd4SqdwDLAwdKDEDHAHd0DsDUo5I59CdxSAyZtckMA+QEEcAdQCBbh6tstFCNexpvNHQgDHQ9AQe6DwdJDJdhDOdGtaDgdGDoDhDJd0Ji8QBwhKDJ9xSRuU+5w9SYyZtCg7OOpnOXMKkXUss8p8Q-wCg9gmgfwAIi4XQr9HAjATAXQOgBcLiju9hqeHUr9ihDDWAmgrCxglI2QfgsI3U+QVufOt2HiVMFAAlusIT6VaaOAXIKiiYYQEQ4CwT0TgilISZwyR5SCSecqujoOuGSTHjXg2JkUlNatcNOtkpURMRzjHuieNAHUIeUNdT9h3NjjdD2A7+HQ6sfe9hUNVTpqJTsemgGs3NWSzk+1IIde+QUolQYNZTmA1GFT8NbTlKHTK8IIf89cNAkBLkRRwkf8i8mz4+5qIIFxGza+5yOzWAFx+z1pZ+ykOgSIiqHA6zvcapGpLzNRMA3w6cyRewbxlIGkMAK1jx6czxfOrasM2jZwowlDgL1AO81IALK1pFkT5FcTYxbcyx6cJzTx-09RYL-wEL8powGMlmsAvcVzvcBJZIlLT0y8CgSNUCUAXU3UpQs2oFra+jDgRjxStY2TaAXgSA2TAiUwrT5jzAVjrgNjpC9jtTtCMNJMzjXTctbjVonj3jvj-jgTEaYToT1MAlKLMTXgk1CTOrMTqT06qZaquG2TcqeTWJeAig0TosxTdDpT2smgCzszVT5tFCSejTctDTweTTsrr95IyznT9TNAvT0NUe6tAzQzjefhLkgRWAEzUzMz2s8znuizYbKziRuzT0GzWz+cKbj0w4+zWzRzwkJzNAZzy8pbVzCt4+Udpb2TJwrxdAFjLadkmlLa-wQI9zckASTzhb7z6p6k7zpRvz3zy1cAXzUxiL52wLNUAM+Lrg+sra7bcAso0LBAVAfzXgi7CTKLxoaLy7QxWLDr9cOL0ca7aAG7-wW7O7JLyUWAl7igi8lLoUJxNL5bHgDL3JvgGMw4nLhj2kHAtYf8wrZjFjEr6sm1707Lj7pwpxBgTA3bpwsM2TQImABgsMQ7bFcOpcQ8mI2IYIuIEISk-7ykoHf2GQyUHARuSjbZIA2x+MaAyAoAtkz8YLjA5CyAIAuYDQ9kHHHQIAqoSSzw0IMOfsyAbUnQvAwQg1nJOA5OaILArapAQ0kEvsaIAnygU0EALHwTBiOmrgMOcAkM5Cg2+0B8AnYAugLHfCylfOrtkEyAYguYckYnwg6gyMdk-UUnKHv4Y4HnXnCnvn0IfsVAdGLAuWYX8xYnS+9AAnp0g1FALH2gX5BieA-ZqQyApSSXfickBidkmgAnLgck9AbqLHrAuWrn2xHHKASC-AY4uAuALHFjRgcArnUE7nSAnniXD8CFeAcn9A7UYnbQaIMXcX8ACX3nIAZazQOXeXyA8qi3dklAfsGMjGygAnrgkiLHpQtKI2TXg3C3ig7UI+CGMA0IHOOkASzt+C83Fw5wQAA), the variable names are mangled and there aren't any comments on the obfuscated sections, making it harder for us to contribute :(

**Comment by CST1229** [comment]
It isn't, it's obfuscated!

**Comment by LankyBox01** [comment]
> It isn't, but parts of it are _**OBFUSCATED**_!!
> (Why have it be open source if we can't even contribute to it anyways?)

i only obfuscated parts that won't be changed. I actually advise any contributor to obfuscate their code if it's related to the admin panel or the site security.

**Comment by CST1229** [comment]
> i only obfuscated parts that won't be changed. I actually advise any contributor to obfuscate their code if it's related to the admin panel or the site security.

I don't think, for example, the code that converts JSON into a page needs to be obfuscated (except for the admin panel).

**Comment by LankyBox01** [comment]
> > i only obfuscated parts that won't be changed. I actually advise any contributor to obfuscate their code if it's related to the admin panel or the site security.
> 
> I don't think, for example, the code that converts JSON into a page needs to be obfuscated (except for the admin panel).

only part obfuscated was the variables to hide the admin panel info. I had to obfuscate the entire set of variables so it is not obvious which is which



> > > It isn't, but parts of it are _**OBFUSCATED**_!!
> > > (Why have it be open source if we can't even contribute to it anyways?)
> > 
> > 
> > i only obfuscated parts that won't be changed. I actually advise any contributor to obfuscate their code if it's related to the admin panel or the site security.
> 
> out of curiosity, what would happen if those parts weren't obfuscated?

anyone could set maintenance on your site and basically entire chaos
Like if everyone suddenly had admin panel access and permission on scratch

**Comment by gosoccerboy5** [comment]
How would they be able to set maintenance on your site if they're only viewing the generated HTML file and not able to edit the index.js

**Comment by gosoccerboy5** [comment]
and why do https://github.com/LankyBox01/ImpactJSON/blob/04dd82824a819d38c65e6696cf3dc8414834f494/index.js#L16-L23 have to be obfuscated as well, if they're unrelated to the admin panel?

**Comment by CST1229** [comment]
> 
> 
> and why do
> 
> https://github.com/LankyBox01/ImpactJSON/blob/04dd82824a819d38c65e6696cf3dc8414834f494/index.js#L16-L23
> have to be obfuscated as well, if they're unrelated to the admin panel?

> only part obfuscated was the variables to hide the admin panel info. I had to obfuscate the entire set of variables so it is not obvious which is which

**Comment by LankyBox01** [comment]
> How would they be able to set maintenance on your site if they're only viewing the generated HTML file and not able to edit the index.js

they cannot. I can only set it. If they want maintenace, replace the to home content with the word "maintenance", i don't care

**Comment by CST1229** [comment]
> 
> 
> How would they be able to set maintenance on your site if they're only viewing the generated HTML file and not able to edit the index.js

By making a POST manually, or by executing edited code that creates the admin panel in the console, or by having the necessary localstorage keys and stuff
